global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'license-service'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['spring-app:8080']
  - job_name: 'organization-service'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['organization-server:8081']